src/main/java/org/team1540/base/power/PowerManager.java

Title. No significant feature changes. The number of commits is slightly inflated due to the many debugging commits I made.

Minor bugfixes and improvements

---

build.gradle
gradle.properties

No feature changes, just debugging.

JitPack fix

---

README.md

Fancy! And they link to things.

Add fancy README images

---

src/main/java/org/team1540/base/wrappers/ChickenTalon.java

Fixed PID setting wrong D

---

.idea/modules/ROOSTER_main.iml
.idea/modules/ROOSTER_test.iml
src/main/java/org/team1540/base/adjustables/AdjustableManager.java
src/main/java/org/team1540/base/testing/AdjustableTestRobot.java
src/main/java/org/team1540/base/util/SimpleLoopCommand.java

Now doesn't require you to call `update()`, instead just creates a looping command that updates.
Also, I created `SimpleLoopCommand`.

Improve AdjustableManager

---

README.md

Add a rooster to ROOSTER

---

src/main/java/org/team1540/base/adjustables/AdjustableManager.java

I'm dumb and forgot to make it run when the bot is disabled.

Fix bug in AdjustableManager updating

---

.idea/modules/ROOSTER_main.iml
.idea/modules/ROOSTER_test.iml
build.gradle
src/main/java/org/team1540/base/Utilities.java
src/main/java/org/team1540/base/drive/PidDrive.java

It is now "not bad" because it scales the deadzoned bit. Keeping the old one around because we respect backwards compatibility. Because I wanted fancy equations, this also adds a MathJax renderer to the generated Javadoc files.
Since the fancy TeX Javadoc doesn't render in IDE's, we may want to find a solution such as deploying a copy of the Javadoc to a Github Page with Travis.

Create new deadzone function

---

src/main/java/org/team1540/base/motionprofiling/MotionProfilingProperties.java
src/main/java/org/team1540/base/motionprofiling/RunMotionProfiles.java

- Fix buggy end checking
- Migrate from encoderTicksPerRev and wheelDiameter to encoderTicksPerUnit

Bug and minor field update

---

.idea/modules/ROOSTER_main.iml
.idea/modules/ROOSTER_test.iml
build.gradle

Update GradleRIO version

---

build.gradle

Add some external links and make TeX rendering work better.

Improve javadoc

---

src/main/java/org/team1540/base/drive/PidDrive.java

Method extraction and me not going over code properly FTW. Not sure how this was working before.

Fix bug where brake processing only used left side

---

README.md

Add javadoc link to README

---

src/main/java/org/team1540/base/triggers/SimpleButton.java
src/main/java/org/team1540/base/util/SimpleConditionalCommand.java

It was noticed that these would be helpful in flamingchickens1540/pandora-titan-2018#8. They allow simple creation of `Button` and `ConditionalCommand` instances with lambdas or function references.

Create SimpleButton and SimpleConditionalCommand

---

src/main/java/org/team1540/base/ChickenSubsystem.java

You can now set an upper limit on any given motor's percentOutput.

Format for individual motor properties

---

src/main/java/org/team1540/base/ChickenSubsystem.java
src/main/java/org/team1540/base/drive/PidDrive.java

Basically a replacement for configPeakOutput for ChickenSubsystem.

Support for independent peak output ceilings

---

lib/src/main/java/org/team1540/base/wrappers/RevBlinken.java

This is why I wanted to test. Turns out I missed one.

Add missing Blinken preset

---

.travis.yml
travis-scripts/name-release-files.sh

Automatically deploy JAR artifacts to Github

---

.idea/misc.xml
lib/src/main/java/org/team1540/base/Utilities.java
lib/src/main/java/org/team1540/base/triggers/AxisButton.java
lib/src/main/java/org/team1540/base/triggers/DPadButton.java
lib/src/main/java/org/team1540/base/triggers/SimpleButton.java
lib/src/main/java/org/team1540/base/triggers/StrictDPadButton.java
lib/src/main/java/org/team1540/base/util/SimpleCommand.java
lib/src/main/java/org/team1540/base/util/SimpleConditionalCommand.java
lib/src/main/java/org/team1540/base/util/SimpleLoopCommand.java

Does what it says on the tin. Adds some `@NotNull`/`@Nullable`/`@Contract` annotations everywhere to keep up with things.

Nullability and cleanup

---

.idea/misc.xml
lib/src/main/java/org/team1540/base/util/DashboardUtils.java

Not tested cause I'm too lazy to set up my fake robot but is also a carbon copy of code we used on Pandora so testing is pretty unnecessary.

Create SmartDashboard utilities

---

README.md
lib/src/main/java/org/team1540/rooster/drive/JoystickScaling.java
lib/src/main/java/org/team1540/rooster/drive/PidDrive.java
lib/src/main/java/org/team1540/rooster/drive/package-info.java
lib/src/main/java/org/team1540/rooster/drive/pipeline/Input.java
lib/src/main/java/org/team1540/rooster/drive/pipeline/Output.java
lib/src/main/java/org/team1540/rooster/drive/pipeline/Processor.java
lib/src/main/java/org/team1540/rooster/power/package-info.java
lib/src/main/java/org/team1540/rooster/preferencemanager/package-info.java
lib/src/main/java/org/team1540/rooster/testers/motor/EncoderTester.java
lib/src/main/java/org/team1540/rooster/testers/package-info.java
lib/src/main/java/org/team1540/rooster/triggers/package-info.java
lib/src/main/java/org/team1540/rooster/util/AsyncCommand.java
lib/src/main/java/org/team1540/rooster/util/Executable.java
lib/src/main/java/org/team1540/rooster/util/package-info.java
lib/src/main/java/org/team1540/rooster/wrappers/package-info.java
test/src/main/java/org/team1540/rooster/testing/AsyncCommandTestRobot.java

To ring in the new year, here's a pull request with some miscellaneous cleanup (mostly resolving problems that IntelliJ thinks we should fix, along with a Javadoc link error that didn't get caught).

Miscellanous Cleanup

---

docs/Simple Utilities.md

Add SimpleAsyncCommand docs

---

travis-scripts/name-release-files.sh

I forgot to update it for the new project restructure

Fix name-release-files.sh again

---

travis-scripts/name-release-files.sh

Okay, so I'm an idiot and bad at refactoring. The jars are obviously not named lib.jar, etc. anymore.
Also fix wording lol

Fix name-release-files.sh again again

---

.idea/compiler.xml
build.gradle
src/main/java/org/team1540/rooster/Utilities.java
src/main/java/org/team1540/rooster/adjustables/AdjustableManager.java
src/main/java/org/team1540/rooster/triggers/MultiAxisButton.java
src/main/java/org/team1540/rooster/wrappers/ChickenTalon.java
src/testbots/java/org/team1540/rooster/testing/TestbotLoaderMain.java

Add MultiAxisButton which is similar to AxisButton but takes a list of axes and movement of any axis will trigger the button.

Multi-axis button for phineas

---

build.gradle

Fix build error
